title: Montreal MLOpt
email: MontrealMLOptimization@gmail.com
baseurl: ""
url: "mtl-mlopt.github.io"

future: true

collections:
  current_organizers:
    sort_by: name
  alumnis:
    sort_by: name
  talks_entries:
    output: true
    
defaults:
  -
    scope:
      path: ""
      type: "talks_entries" 
    values:
      layout: "talks"
      hero_height: is-small

# Build settings
# theme: bulma-clean-theme
remote_theme: chrisrhymes/bulma-clean-theme

plugins:
  - jekyll-feed
 
remote_theme: chrisrhymes/bulma-clean-theme

# Theme-related config
lang: en
fixed_navbar: top

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
